apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: nginx-helm-demo
  name: nginx-helm-demo
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: nginx-helm-demo
status:
  loadBalancer: {}
