apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: {{ .Values.labels.app }}
  name: {{ .Values.name }}
spec:
  replicas: {{ .Values.spec.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.spec.selector.matchLabels.app }}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: {{ .Values.spec.template.metadata.labels.app }}
    spec:
      containers:
      - image: {{ .Values.spec.template.spec.containers.image }}
        name: {{ .Values.spec.template.spec.containers.name }}
        resources: {}
status: {}
