# Default values for flux-helm-demo-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
labels:
  app: nginx-helm-demo
name: nginx-helm-demo-2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-helm-demo
  template:
    metadata:
      labels:
        app: nginx-helm-demo
    spec:
      containers:
        image: nginx
        name: nginx